import type { OJSJob, CodegenLanguage } from './types'
import { generateCode } from './codegen/generator'

interface ProjectFile {
  name: string
  content: string
}

const projectConfigs: Record<CodegenLanguage, {
  configFile: string
  configContent: (job: OJSJob) => string
  codeFile: string
  readme: (job: OJSJob) => string
}> = {
  go: {
    configFile: 'go.mod',
    configContent: (job) => `module ${job.type.split('.')[0] ?? 'myapp'}-worker\n\ngo 1.22\n\nrequire github.com/openjobspec/ojs-go-sdk v0.1.0\n`,
    codeFile: 'main.go',
    readme: (job) => `# ${job.type} Worker\n\nOJS job worker generated from the OJS Playground.\n\n## Quick Start\n\n\`\`\`bash\ngo mod tidy\ngo run main.go\n\`\`\`\n`,
  },
  javascript: {
    configFile: 'package.json',
    configContent: (job) => JSON.stringify({
      name: `${job.type.replace(/\./g, '-')}-worker`,
      version: '1.0.0',
      type: 'module',
      scripts: { start: 'node index.js' },
      dependencies: { '@openjobspec/sdk': '^0.1.0' },
    }, null, 2),
    codeFile: 'index.js',
    readme: (job) => `# ${job.type} Worker\n\nOJS job worker generated from the OJS Playground.\n\n## Quick Start\n\n\`\`\`bash\nnpm install\nnpm start\n\`\`\`\n`,
  },
  python: {
    configFile: 'requirements.txt',
    configContent: () => 'openjobspec>=0.1.0\n',
    codeFile: 'worker.py',
    readme: (job) => `# ${job.type} Worker\n\nOJS job worker generated from the OJS Playground.\n\n## Quick Start\n\n\`\`\`bash\npip install -r requirements.txt\npython worker.py\n\`\`\`\n`,
  },
  ruby: {
    configFile: 'Gemfile',
    configContent: () => "source 'https://rubygems.org'\n\ngem 'openjobspec'\n",
    codeFile: 'worker.rb',
    readme: (job) => `# ${job.type} Worker\n\nOJS job worker generated from the OJS Playground.\n\n## Quick Start\n\n\`\`\`bash\nbundle install\nruby worker.rb\n\`\`\`\n`,
  },
  rust: {
    configFile: 'Cargo.toml',
    configContent: (job) => `[package]\nname = "${job.type.replace(/\./g, '-')}-worker"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\nojs-sdk = "0.1"\ntokio = { version = "1", features = ["full"] }\n`,
    codeFile: 'src/main.rs',
    readme: (job) => `# ${job.type} Worker\n\nOJS job worker generated from the OJS Playground.\n\n## Quick Start\n\n\`\`\`bash\ncargo run\n\`\`\`\n`,
  },
  java: {
    configFile: 'pom.xml',
    configContent: (job) => `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>${job.type.replace(/\./g, '-')}-worker</artifactId>
  <version>1.0-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>org.openjobspec</groupId>
      <artifactId>ojs-java-sdk</artifactId>
      <version>0.1.0</version>
    </dependency>
  </dependencies>
</project>`,
    codeFile: 'src/main/java/Worker.java',
    readme: (job) => `# ${job.type} Worker\n\nOJS job worker generated from the OJS Playground.\n\n## Quick Start\n\n\`\`\`bash\nmvn compile exec:java\n\`\`\`\n`,
  },
}

/**
 * Generate starter project files for download.
 */
export function generateProjectFiles(job: OJSJob, language: CodegenLanguage): ProjectFile[] {
  const config = projectConfigs[language]
  const code = generateCode(job, language, 'full')
  const specJson = JSON.stringify(job, null, 2)

  return [
    { name: 'README.md', content: config.readme(job) },
    { name: config.configFile, content: config.configContent(job) },
    { name: config.codeFile, content: code },
    { name: 'spec.json', content: specJson },
  ]
}

/**
 * Download project files as individual file downloads (since we can't create ZIPs without a library).
 * Creates a combined shell-friendly output.
 */
export function downloadProjectAsScript(job: OJSJob, language: CodegenLanguage): void {
  const files = generateProjectFiles(job, language)
  const projectName = `${job.type.replace(/\./g, '-')}-worker`

  // Generate a setup script that creates all files
  let script = `#!/bin/bash\n# OJS Starter Project: ${projectName}\n# Generated by OJS Playground (https://play.openjobspec.org)\n\nset -e\n\nmkdir -p "${projectName}"\ncd "${projectName}"\n\n`

  for (const file of files) {
    // Handle subdirectories
    const dir = file.name.includes('/') ? file.name.substring(0, file.name.lastIndexOf('/')) : null
    if (dir) {
      script += `mkdir -p "${dir}"\n`
    }
    // Escape content for heredoc
    const escaped = file.content.replace(/\\/g, '\\\\').replace(/\$/g, '\\$')
    script += `cat > "${file.name}" << 'OJSEOF'\n${escaped}\nOJSEOF\n\n`
  }

  script += `echo "✅ Project '${projectName}' created successfully!"\necho "   cd ${projectName} && see README.md for next steps"\n`

  const blob = new Blob([script], { type: 'text/x-shellscript' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${projectName}-setup.sh`
  a.click()
  URL.revokeObjectURL(url)
}
